---
title: "iccat-spillover-main"
author: "Julia Lawson, UCSB"
date: "4/27/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(ggpubr)
library(kableExtra)
library(reshape2)
library(fixest)
here()

#Cleaning data
iccat <- read.csv(here("data", "t1nc-ALL_20201218.csv"),
                  stringsAsFactors = F) %>% 
  unite(FleetGear, c(Fleet,GearGrp), sep=".", remove=FALSE)

#Isolating fleets that catch TAC-managed species.
iccat.fleets <- iccat %>% 
  filter(Species == "BFT" | Species == "SWO" | Species == "ALB" | Species == "BET"| Species == "YFT" | Species == "WHM"| Species == "BUM" | Species == "BSH" | Species == "RSP") %>% 
  group_by(Fleet, GearGrp) %>%
  select(Fleet, GearGrp) %>% 
  distinct(Fleet, GearGrp) %>% 
  unite(FleetGear, c(Fleet,GearGrp), sep=".", remove=FALSE)

#Removing general tuna and billfish categories (not identified beyond Genus).
iccat.fil <- left_join(iccat.fleets, iccat, by=c("FleetGear","Fleet","GearGrp")) %>% 
  group_by(FleetGear, ScieName) %>% 
  filter(ScieName != "Thunnini" & ScieName != "Thunnus spp" & ScieName !="Istiophoridae" & ScieName != "Scomberomorus spp")

#Adding TAC year dummy variable, based on year that TAC was implemented (yearTACimp)
iccat_df <- iccat.fil %>%
  mutate(yearTACimp = case_when(
    Species == "BFT" & Stock == "ATW" ~ 1982,
    Species == "SWO" & Stock == "ATN" ~ 1997,
    Species == "SWO" & Stock == "ATS" ~ 1998,
    Species == "ALB" & Stock == "ATS" ~ 1998,
    Species == "BFT" & Stock == "ATE" ~ 1999,
    Species == "ALB" & Stock == "ATN" ~ 2001,
    Species == "BET" & Stock == "A+M" ~ 2005,
    Species == "SBF" & Stock == "A+M" ~ 2006,
    Species == "BUM" & Stock == "A+M" ~ 2013,
    Species == "WHM" & Stock == "A+M" ~ 2013,
    Species == "YFT" & Stock == "ATE" ~ 2013,
    Species == "YFT" & Stock == "ATW" ~ 2013,
    Species == "SWO" & Stock == "MED" ~ 2017,
    Species == "BSH" & Stock == "ATN" ~ 2019,
    Species == "BSH" & Stock == "ATS" ~ 2019)) %>%
    mutate(yearTACimp = ifelse(is.na(yearTACimp), 
                                   Inf, yearTACimp),
           tacr = 1 * (YearC >= yearTACimp)) %>% 
  mutate(tacever = case_when(
    Species == "BFT" & Stock == "ATW" ~ 1,
    Species == "SWO" & Stock == "ATN" ~ 1,
    Species == "SWO" & Stock == "ATS" ~ 1,
    Species == "ALB" & Stock == "ATS" ~ 1,
    Species == "BFT" & Stock == "ATE" ~ 1,
    Species == "ALB" & Stock == "ATN" ~ 1,
    Species == "BET" & Stock == "A+M" ~ 1,
    Species == "SBF" & Stock == "A+M" ~ 1,
    Species == "BUM" & Stock == "A+M" ~ 1,
    Species == "WHM" & Stock == "A+M" ~ 1,
    Species == "YFT" & Stock == "ATE" ~ 1,
    Species == "YFT" & Stock == "ATW" ~ 1,
    Species == "SWO" & Stock == "MED" ~ 1,
    Species == "BSH" & Stock == "ATN" ~ 1,
    Species == "BSH" & Stock == "ATS" ~ 1)) %>%
    mutate(tacever = ifelse(is.na(tacever), 0, tacever))

#Accumulation of stocks over time, increase in reporting.
iccat_1970 <- iccat_df %>% 
  filter(YearC == 1970) %>% 
  ungroup() %>% 
  distinct(ScieName)
iccat_2019 <- iccat_df %>% 
  filter(YearC == 2019) %>% 
  ungroup() %>% 
  distinct(ScieName)
incommon <- inner_join(iccat_2019, iccat_1970)

#There are 63 stock groups that have been added between 1970 and 2019. I am removing them so that the numbers are not inflated as new stocks are reported over time. Only stocks that are "in common" in 1970 and 2019 will be retained. 

iccat_df_final <- left_join(incommon, iccat_df, by="ScieName") %>% 
  unite(SpeciesStock, c(Species,Stock), sep=".", remove=FALSE)

#Creating a tac_any column, which shows in a given fleet year (grouped by FleetGear and YearC) if there are any stocks that are catch regulated (1 if at least one TAC-regulated stock is in the catch, 0 if none)
iccat_df_final_edit <- iccat_df_final %>%
  group_by(YearC, FleetGear) %>% 
  mutate(tac_any = case_when(any(tacr == 1) ~ 1, TRUE ~ 0))

iccat_df_final_edit_ex <- iccat_df_final_edit %>% 
  filter(tacr==0)

```


```{r analysis}

#Regression 1. ----
#Question: Does the catch of fleets that are catching one or more TAC stock increase or decrease relative to fleets that do not catch any TAC stocks?
#Answer from the regression output: Fleets that catch one or more TAC stock increase their catch by 10.89 metric tons, relative to fleets that do not catch any TAC stocks.

# tac_reg1 <- lm(Qty_t ~ tac_any + as.factor(YearC) + FleetGear + SpeciesStock, data = filter(iccat_df_final_edit, tacr==0))
# summary(tac_reg1) #matches feols output
#mb, 5.3.21: commenting out for speed, made YearC into a categorical FE

tac_reg1b <- feols(Qty_t ~ tac_any | YearC + FleetGear + SpeciesStock, data = filter(iccat_df_final_edit, tacr==0))
coef_tab <- tac_reg1b$coeftable

tac_reg1c <- feols(Qty_t ~ tac_any | YearC^SpeciesStock + FleetGear, data = filter(iccat_df_final_edit, tacr==0)) #mb: adding year-by-speciesstock FEs
coef_tab <- tac_reg1c$coeftable
#result: positive, significant spillover when adding FEs that account for variations in stock-by-year
#JML: Answer from regression output: The total catch of non-TAC regulated stocks (SpeciesStock) increases by 113.40 metric tons for fleets (FleetGear) that catch at least one TAC managed stock (tac_any = 1), when SpeciesStock is interacted with year.

#Regression 2. ----
#Creating a column that is proportion of TAC-treated stocks in total catch (prop_tacC).
iccat_df_final_test2 <- iccat_df_final_edit %>% 
  group_by(YearC, FleetGear) %>% 
  mutate(totalCatch = sum(Qty_t),
         tac_catch = sum(Qty_t[tacr==1])) %>% #Total catch grouped by FleetGear and YearC
  mutate(prop_tacC = tac_catch/totalCatch) #mb: notice this is different

hist(iccat_df_final_test2$prop_tacC)

# mb: leaving some old code that is probably wrong  
#   filter(tacr == 1) %>% 
#   group_by(YearC, FleetGear) %>% 
#   mutate(prop_tacC = Qty_t/totalCatch) %>%
#   # select(YearC, FleetGear, SpeciesStock, prop_tacC)
#   select(YearC, FleetGear, prop_tacC) #mb: should only merge on Year and FleetGear
# 
# hist(iccat_df_final_test2$prop_tacC)
# 
# #Adding back into full dataset
# iccat_df_final_reg <- iccat_df_final_edit %>% 
#   left_join(.,iccat_df_final_test2) #%>% 
#   # mutate(prop_tacC = if_else(is.na(prop_tacC), 0, prop_tacC)) #unnecessary, zeros created by merge error in previous step
# 
# table(see$prop_tacC)

iccat_df_final_reg <- iccat_df_final_test2

#Question. Does the catch of fleets that are catching one or more TAC stock increase or decrease relative to fleets that do not catch any TAC stocks when we account for the relative proportion of TAC-treated stocks in the catch?
#Answer from the regression: Got stuck here - the proportion variable (prop_tacC) was removed due to collinearity.

# tac_reg2 <- lm(Qty_t ~ tac_any*prop_tacC + as.factor(YearC) + FleetGear + SpeciesStock, data = filter(iccat_df_final_reg, tacr==0))
# summary(tac_reg2)
# 
# tac_reg2b <- feols(Qty_t ~ tac_any*prop_tacC | YearC + FleetGear + SpeciesStock, data = filter(iccat_df_final_reg, tacr==0))
# # print(tac_reg2b)

tac_reg2c <- feols(Qty_t ~ prop_tacC | YearC^SpeciesStock + FleetGear, data = filter(iccat_df_final_reg, tacr==0))
coef_tab <- tac_reg2c$coeftable

#note: this isn't strictly right, because we probably want the dosage based on the pre-treatment period only

```
